/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as WorkshopIdRouteImport } from './routes/workshop.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopIdRoute = WorkshopIdRouteImport.update({
  id: '/workshop/$id',
  path: '/workshop/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workshops': typeof WorkshopsRoute
  '/workshop/$id': typeof WorkshopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workshops': typeof WorkshopsRoute
  '/workshop/$id': typeof WorkshopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workshops': typeof WorkshopsRoute
  '/workshop/$id': typeof WorkshopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workshops' | '/workshop/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workshops' | '/workshop/$id'
  id: '__root__' | '/' | '/workshops' | '/workshop/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkshopsRoute: typeof WorkshopsRoute
  WorkshopIdRoute: typeof WorkshopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop/$id': {
      id: '/workshop/$id'
      path: '/workshop/$id'
      fullPath: '/workshop/$id'
      preLoaderRoute: typeof WorkshopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkshopsRoute: WorkshopsRoute,
  WorkshopIdRoute: WorkshopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
